Update check-welcome-file.yml

diff --git a/.github/.workflows/check-welcome-file.yml b/.github/.workflows/check-welcome-file.yml
--- a/.github/.workflows/check-welcome-file.yml
+++ b/.github/.workflows/check-welcome-file.yml
@@ -1,1 +1,40 @@
+name: Create and Check File
 
+on: push
+
+jobs:
+  create_and_check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Create welcome.yml file
+        run: |
+          if [ ! -f .github/workflows/welcome.yml ]; then
+            echo "name: Welcome Workflow" > .github/workflows/welcome.yml
+          fi
+
+      - name: Check file content
+        env:
+          FILE: .github/workflows/welcome.yml
+          SEARCH: name:
+        run: |
+          echo "Check that all required env variables are set"
+          if [ -z "$FILE" ]; then
+            echo "FILE is unset or set to the empty string"
+            exit 1
+          fi
+          if [ -z "$SEARCH" ]; then
+            echo "SEARCH is unset or set to the empty string"
+            exit 1
+          fi
+          echo "Check that $FILE includes $SEARCH"
+          if grep --perl-regexp "$SEARCH" -- $FILE; then
+            echo "Found $SEARCH in $FILE"
+          else
+            echo "Missing $SEARCH in $FILE"
+            echo "----------------"
+            echo "$(cat $FILE)"
+            exit 204
+          fi
